2025-06-03 00:01:00 +0000 - dagster - DEBUG - commodities_job - 38e64c8c-a7a9-43f1-85cf-0c8f8991776a - 34434 - LOGS_CAPTURED - Started capturing logs in process (pid: 34434).
2025-06-03 00:01:00 +0000 - dagster - DEBUG - commodities_job - 38e64c8c-a7a9-43f1-85cf-0c8f8991776a - 34434 - train_commodities - STEP_START - Started execution of step "train_commodities".
2025-06-03 00:01:00 +0000 - dagster - INFO - commodities_job - 38e64c8c-a7a9-43f1-85cf-0c8f8991776a - train_commodities - MLflow Tracking URI: http://mlflow:5000
2025-06-03 00:01:00 +0000 - dagster - INFO - commodities_job - 38e64c8c-a7a9-43f1-85cf-0c8f8991776a - train_commodities - MLflow S3 Endpoint: http://minio:9000
2025-06-03 00:01:00 +0000 - dagster - ERROR - commodities_job - 38e64c8c-a7a9-43f1-85cf-0c8f8991776a - 34434 - train_commodities - STEP_FAILURE - Execution of step "train_commodities" failed.

dagster._core.errors.DagsterExecutionStepExecutionError: Error occurred while executing op "train_commodities"::

FileNotFoundError: [Errno 2] No such file or directory: 'data/commodities.csv'

Stack Trace:
  File "/usr/local/lib/python3.10/site-packages/dagster/_core/execution/plan/utils.py", line 54, in op_execution_error_boundary
    yield
  File "/usr/local/lib/python3.10/site-packages/dagster/_utils/__init__.py", line 467, in iterate_with_context
    next_output = next(iterator)
  File "/usr/local/lib/python3.10/site-packages/dagster/_core/execution/plan/compute_generator.py", line 131, in _coerce_op_compute_fn_to_iterator
    result = invoke_compute_fn(
  File "/usr/local/lib/python3.10/site-packages/dagster/_core/execution/plan/compute_generator.py", line 125, in invoke_compute_fn
    return fn(context, **args_to_pass) if context_arg_provided else fn(**args_to_pass)
  File "/opt/dagster/app/cd4ml_pipeline/ops/commodities_ops.py", line 15, in train_commodities
    df = pd.read_csv("data/commodities.csv")
  File "/usr/local/lib/python3.10/site-packages/pandas/util/_decorators.py", line 211, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/pandas/util/_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 950, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/usr/local/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 605, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/usr/local/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1442, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/usr/local/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1735, in _make_engine
    self.handles = get_handle(
  File "/usr/local/lib/python3.10/site-packages/pandas/io/common.py", line 856, in get_handle
    handle = open(

